class ExitRound(Exception):
    pass


class ExitLoop(Exception):
    pass
